functionsDirectory = "/Users/danb/Documents/PROJECTS/TEST_PROJECTS/Personal Management Time/netlify/functions"
functionsDirectoryOrigin = "config-v1"
redirectsOrigin = "config"
plugins = []
headers = []

[build]
publish = "/Users/danb/Documents/PROJECTS/TEST_PROJECTS/Personal Management Time/dist"
publishOrigin = "config"
commandOrigin = "config"
command = "npm run build"
functions = "/Users/danb/Documents/PROJECTS/TEST_PROJECTS/Personal Management Time/netlify/functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[functions]

[functions."*"]
node_bundler = "esbuild"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]